# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('head_line', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
